---
title: "HW1"
author: "Xilong Li (3467966)"
date: '2022-04-02'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Machine Learning Main Ideas

### Qestion 1
1) Supervised learning means that there is an existing labeled dataset that can be learned from, as if there is an "answer key" such that we can "supervised" the machine on its accuracy of prediction and modeling.    
2) Unsupervised learning means that there is no such labeled dataset that can be learned from. Thus, we cannot "supervise" its learning because we don't even know what the data should look like.

Another difference between supervised and unsupervised learning is that, while supervised learning involves regression and classification to establish models, unsupervised learning uses methods such as clustering to learn from unknown models. 

### Qestion 2
1) For the regression model, the response variable is quantitative, which means that it is numeric and can be directly calculated. Thus, the regression model allows us to predict trans based on existing labeled data. For example, we can use the existing data to establish model about the gas price for next month.
2) For the classification model, the response variable is qualitative, so it cannot be directly calculated as numbers. For example, classification model can be established on issues about whether a person is graduate or not, which is not numeric and is thus qualitative.

### Qestion 3

### Qestion 4

### Qestion 5

### Qestion 6

## Exploratory Data Analysis

### Qestion 1

### Qestion 2

### Qestion 3

### Qestion 4

### Qestion 5